2017-08-24 08:20:13,014 INFO 17447 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
2017-08-24 08:20:13,956 WARNING 17447 [py.warnings] base.py:260 - /opt/lms_edx/edx-ficus.3-3/apps/edx/venvs/edxapp/lib/python2.7/site-packages/django/core/management/base.py:260: RemovedInDjango19Warning: "requires_model_validation" is deprecated in favor of "requires_system_checks".
  RemovedInDjango19Warning)

2017-08-24 08:20:15,454 WARNING 17447 [py.warnings] worker.py:161 - /opt/lms_edx/edx-ficus.3-3/apps/edx/venvs/edxapp/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

2017-08-24 08:20:15,546 INFO 17447 [celery.worker.consumer] consumer.py:479 - Connected to amqp://bn_edx:**@127.0.0.1:5672//
2017-08-24 08:20:15,601 INFO 17447 [celery.worker.consumer] consumer.py:567 - mingle: searching for neighbors
2017-08-24 08:20:16,631 INFO 17447 [celery.worker.consumer] consumer.py:585 - mingle: all alone
2017-08-24 08:20:16,676 WARNING 17447 [celery.redirected] log.py:282 - celery@edx.cms.core.default.LMS-SRV ready.
2017-08-24 08:20:30,218 INFO 17447 [celery.worker.strategy] strategy.py:55 - Received task: certificates.signals.enable_self_generated_certs[2ebb9712-c3ef-4b54-8475-dbe61413ec16]
2017-08-24 08:20:30,222 ERROR 17447 [celery.worker.consumer] consumer.py:427 - Received unregistered task of type u'openedx.core.djangoapps.content.course_structures.tasks.update_course_structure'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [u'course-v1:edX+DemoX+Demo_Course'], u'retries': 0, u'expires': None, u'task': u'openedx.core.djangoapps.content.course_structures.tasks.update_course_structure', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'950ab322-eedf-4d62-b3ef-156647f0f167'} (349b)
Traceback (most recent call last):
  File "/opt/lms_edx/edx-ficus.3-3/apps/edx/venvs/edxapp/lib/python2.7/site-packages/celery/worker/consumer.py", line 455, in on_task_received
    strategies[name](message, body,
KeyError: u'openedx.core.djangoapps.content.course_structures.tasks.update_course_structure'
2017-08-24 08:20:30,295 INFO 17447 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.content.block_structure.tasks.update_course_in_cache[8b449399-41ad-46c7-bf3b-919436fe9f22] eta:[2017-08-24 08:21:00.228437-04:00]
2017-08-24 08:20:30,364 INFO 17447 [celery.worker.strategy] strategy.py:55 - Received task: lms.djangoapps.certificates.signals.enable_self_generated_certs[cfb1f257-f5bb-4574-871a-c4b096f23ade]
2017-08-24 08:20:31,231 INFO 17696 [openedx.core.djangoapps.content.course_overviews.models] models.py:118 - Creating course overview for course-v1:edX+DemoX+Demo_Course.
2017-08-24 08:20:31,254 INFO 17447 [celery.worker.job] job.py:401 - Task certificates.signals.enable_self_generated_certs[2ebb9712-c3ef-4b54-8475-dbe61413ec16] succeeded in 1.03284765s: None
2017-08-24 08:20:31,344 INFO 17694 [openedx.core.djangoapps.content.course_overviews.models] models.py:118 - Creating course overview for course-v1:edX+DemoX+Demo_Course.
2017-08-24 08:20:31,366 INFO 17447 [celery.worker.job] job.py:401 - Task lms.djangoapps.certificates.signals.enable_self_generated_certs[cfb1f257-f5bb-4574-871a-c4b096f23ade] succeeded in 0.999396536994s: None
2017-08-24 08:20:41,066 INFO 17447 [celery.worker.strategy] strategy.py:55 - Received task: certificates.signals.enable_self_generated_certs[3a0faa49-d997-4165-893e-32ed3ec5f8c0]
2017-08-24 08:20:41,100 INFO 17447 [celery.worker.job] job.py:401 - Task certificates.signals.enable_self_generated_certs[3a0faa49-d997-4165-893e-32ed3ec5f8c0] succeeded in 0.0324637390004s: None
2017-08-24 08:20:41,175 ERROR 17447 [celery.worker.consumer] consumer.py:427 - Received unregistered task of type u'openedx.core.djangoapps.content.course_structures.tasks.update_course_structure'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [u'course-v1:edX+DemoX+Demo_Course'], u'retries': 0, u'expires': None, u'task': u'openedx.core.djangoapps.content.course_structures.tasks.update_course_structure', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'b0eff233-8499-497d-a63c-f9ea89558984'} (349b)
Traceback (most recent call last):
  File "/opt/lms_edx/edx-ficus.3-3/apps/edx/venvs/edxapp/lib/python2.7/site-packages/celery/worker/consumer.py", line 455, in on_task_received
    strategies[name](message, body,
KeyError: u'openedx.core.djangoapps.content.course_structures.tasks.update_course_structure'
2017-08-24 08:20:41,282 INFO 17447 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.content.block_structure.tasks.update_course_in_cache[e5a72a0a-9245-4869-afd5-9d92b05fc9da] eta:[2017-08-24 08:21:11.179397-04:00]
2017-08-24 08:20:41,391 INFO 17447 [celery.worker.strategy] strategy.py:55 - Received task: lms.djangoapps.certificates.signals.enable_self_generated_certs[bd252ef6-468d-4d5f-9392-15870e93416b]
2017-08-24 08:20:42,369 INFO 17695 [openedx.core.djangoapps.content.course_overviews.models] models.py:118 - Creating course overview for course-v1:edX+DemoX+Demo_Course.
2017-08-24 08:20:42,392 INFO 17447 [celery.worker.job] job.py:401 - Task lms.djangoapps.certificates.signals.enable_self_generated_certs[bd252ef6-468d-4d5f-9392-15870e93416b] succeeded in 0.998826965995s: None
2017-08-24 08:20:43,348 INFO 17447 [celery.worker.strategy] strategy.py:55 - Received task: certificates.signals.enable_self_generated_certs[32523ffe-243f-41b3-a542-63e52fbec5bb]
2017-08-24 08:20:43,359 INFO 17447 [celery.worker.job] job.py:401 - Task certificates.signals.enable_self_generated_certs[32523ffe-243f-41b3-a542-63e52fbec5bb] succeeded in 0.00951526800054s: None
2017-08-24 08:20:43,410 ERROR 17447 [celery.worker.consumer] consumer.py:427 - Received unregistered task of type u'openedx.core.djangoapps.content.course_structures.tasks.update_course_structure'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [u'course-v1:edX+DemoX+Demo_Course'], u'retries': 0, u'expires': None, u'task': u'openedx.core.djangoapps.content.course_structures.tasks.update_course_structure', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'c7593120-5779-409c-9fa1-5e221fc3818b'} (349b)
Traceback (most recent call last):
  File "/opt/lms_edx/edx-ficus.3-3/apps/edx/venvs/edxapp/lib/python2.7/site-packages/celery/worker/consumer.py", line 455, in on_task_received
    strategies[name](message, body,
KeyError: u'openedx.core.djangoapps.content.course_structures.tasks.update_course_structure'
2017-08-24 08:20:43,470 INFO 17447 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.content.block_structure.tasks.update_course_in_cache[55b4487f-01a8-4aad-9a74-d085ff4ef3a0] eta:[2017-08-24 08:21:13.414409-04:00]
2017-08-24 08:20:43,648 INFO 17447 [celery.worker.strategy] strategy.py:55 - Received task: lms.djangoapps.certificates.signals.enable_self_generated_certs[59f3a9e9-ee06-4176-8df2-d34a5afa779f]
2017-08-24 08:20:43,659 INFO 17447 [celery.worker.job] job.py:401 - Task lms.djangoapps.certificates.signals.enable_self_generated_certs[59f3a9e9-ee06-4176-8df2-d34a5afa779f] succeeded in 0.00971073099936s: None
2017-08-24 08:21:01,313 INFO 17697 [openedx.core.lib.block_structure.cache] cache.py:121 - Deleted BlockStructure BlockUsageLocator(CourseLocator(u'edX', u'DemoX', u'Demo_Course', None, None), 'course', 'course') from the cache.
2017-08-24 08:21:01,314 INFO 17697 [openedx.core.lib.block_structure.cache] cache.py:89 - Did not find BlockStructure BlockUsageLocator(CourseLocator(u'edX', u'DemoX', u'Demo_Course', None, None), 'course', 'course') in the cache.
2017-08-24 08:21:02,717 INFO 17697 [openedx.core.lib.block_structure.cache] cache.py:61 - Wrote BlockStructure block-v1:edX+DemoX+Demo_Course+type@course+block@course to cache, size: 24858
2017-08-24 08:21:02,719 INFO 17447 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.content.block_structure.tasks.update_course_in_cache[8b449399-41ad-46c7-bf3b-919436fe9f22] succeeded in 2.208699029s: None
2017-08-24 08:21:11,637 INFO 17695 [openedx.core.lib.block_structure.cache] cache.py:121 - Deleted BlockStructure BlockUsageLocator(CourseLocator(u'edX', u'DemoX', u'Demo_Course', None, None), 'course', 'course') from the cache.
2017-08-24 08:21:11,638 INFO 17695 [openedx.core.lib.block_structure.cache] cache.py:89 - Did not find BlockStructure BlockUsageLocator(CourseLocator(u'edX', u'DemoX', u'Demo_Course', None, None), 'course', 'course') in the cache.
2017-08-24 08:21:12,984 INFO 17695 [openedx.core.lib.block_structure.cache] cache.py:61 - Wrote BlockStructure block-v1:edX+DemoX+Demo_Course+type@course+block@course to cache, size: 24899
2017-08-24 08:21:12,986 INFO 17447 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.content.block_structure.tasks.update_course_in_cache[e5a72a0a-9245-4869-afd5-9d92b05fc9da] succeeded in 1.35057645s: None
2017-08-24 08:21:13,641 INFO 17696 [openedx.core.lib.block_structure.cache] cache.py:121 - Deleted BlockStructure BlockUsageLocator(CourseLocator(u'edX', u'DemoX', u'Demo_Course', None, None), 'course', 'course') from the cache.
2017-08-24 08:21:13,642 INFO 17696 [openedx.core.lib.block_structure.cache] cache.py:89 - Did not find BlockStructure BlockUsageLocator(CourseLocator(u'edX', u'DemoX', u'Demo_Course', None, None), 'course', 'course') in the cache.
2017-08-24 08:21:14,954 INFO 17696 [openedx.core.lib.block_structure.cache] cache.py:61 - Wrote BlockStructure block-v1:edX+DemoX+Demo_Course+type@course+block@course to cache, size: 24857
2017-08-24 08:21:14,956 INFO 17447 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.content.block_structure.tasks.update_course_in_cache[55b4487f-01a8-4aad-9a74-d085ff4ef3a0] succeeded in 1.31696498899s: None
